### ISSUE TITLE
Kernel panic

### ISSUE THREAD

**Issue by cassiebaer** [ashaffer/rt3573sta#2]
Hey, thanks a lot for uploading this! I'd been searching for ways to fix the kernel panic for some time before I stumbled on this; unfortunately, I am still getting a kernel panic. But this seems more promising than anything else I have found...

```
kernel BUG at net/core/skbuff.c:127!
invalid opcode: 0000 [#1] PREEMPT SMP
...
```

I tried to make sense of your changes to the original driver, but know nothing of kernel development. Could you help me reason through it or point me in the right direction to figuring this out myself?

Thanks!

edit: I forgot to mention that I am using an AE3000 usb device.

**Comment by ashaffer** [comment]
I'm not sure how much help I can be with this one.  If the error 'invalid opcode' that its reporting is correct, it likely means you're compiling it incorrectly, or there is something very strange going on that's causing it to jump into the middle of an instruction somewhere.

One thing to note is that it appears to be coming from skbuff.c, which has a relatively limited number of entry points from this driver.  I would suggest putting DBGPRINT statements surrounding all of the areas where skbuff functions are accessed from the driver (these prints will show up in the dmesg log).  Hopefully this will at least allow you to narrow it down to a particular function.  This is what I did to debug the original issue.  It was extremely tedious, but ultimately fruitful.
